version: '3.7'
services:
  rest_service:
    build:
      context: '.'
      dockerfile: Dockerfile
    image: ghcr.io/kenesparta/tk_rest_service
    container_name: rest_service
    restart: "no"
    ports:
      - "8084:8084"
