name: Accepting PR

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: docker build
        run: |
          docker build -t kenesparta/tk_rest_service:latest .
